# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=70)),
                ('store_type', models.CharField(default='General', max_length=40)),
                ('store_link', models.URLField()),
            ],
        ),
    ]
