# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_logo',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
